version: "3.9"

services:
  postgres:
    image:  postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: mydatabase
    volumes:
      - ./data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8089:80"
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: bis_henrique@yahoo.com.br
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_DEFAULT_USERNAME: admin
      PGADMIN_APP_PORT: 80
      PGADMIN_SERVER_PORT: 5432
      PGADMIN_CONNECT_STRING: postgres://postgres:password@postgres:5432/mydb
volumes:
  postgres-data:
